-module(problem2).
-export([fib/1]).
%
% % Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
%
% % 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%
% % By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


fib(Max) ->
    fib_sequence(Max, 1, 1, 0).

% fib_sequence(Max, Curr, Prev, Total) ->
%   case fib_max(Max, Curr) of
%       true ->
%         Total;
%       _ when Curr rem 2 =:= 0 ->
%         fib_sequence(Max, Curr + Prev, Curr, Total + Curr);
%       _ ->
%         fib_sequence(Max, Curr + Prev, Curr, Total)
%   end.
%
% fib_max(Max, Curr) when Curr > Max ->
%   true;
% fib_max(Max, Curr) when Curr < Max ->
%   false.

fib_sequence(Max, Curr, _, Total) when Curr > Max ->
  Total;
fib_sequence(Max, Curr, Prev, Total) when Curr rem 2 =:= 0 ->
  fib_sequence(Max, Curr + Prev, Curr, Total + Curr);
fib_sequence(Max, Curr, Prev, Total) ->
  fib_sequence(Max, Curr + Prev, Curr, Total).
